# Generated by Django 2.1.7 on 2019-03-04 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('isAdmin', models.BooleanField(default=True)),
                ('maxAccountCount', models.IntegerField(default=100)),
                ('mobile_number', models.CharField(max_length=11)),
                ('credit', models.IntegerField(default=1000)),
                ('accounts', models.ManyToManyField(to='register.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='accounts',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
