# Generated by Django 2.1.7 on 2019-03-04 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20190304_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='password',
            new_name='isim',
        ),
        migrations.RemoveField(
            model_name='client',
            name='isAdmin',
        ),
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
    ]
