# Generated by Django 2.1.7 on 2019-03-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20190304_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='picture',
        ),
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_pics'),
        ),
    ]
