# Generated by Django 2.1.7 on 2019-03-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20190304_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='shared_photos'),
        ),
    ]
