# Generated by Django 2.1.7 on 2019-03-04 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20190304_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Client'),
        ),
    ]
